import generate from "../../commands/generate.ts";
import { forEachAdapter, runCommand } from "./utils.ts";
import log from "../../lib/log.ts";

/**
 * Options for generating themes in repositories
 */
export interface AdaptRepositoriesOptions {
    /** Whether to commit changes (default: true) */
    commit?: boolean;
}

/**
 * Generate themes for all repositories and optionally commit changes
 */
export async function generateAllRepositories(options: AdaptRepositoriesOptions = {}) {
    const { commit = true } = options;

    const title = commit
        ? "Generating themes for all repositories with commit..."
        : "Generating themes for all repositories without commit...";

    await forEachAdapter(
        async ({ adapter, adapterName }) => {
            await generate();

            // Check for changes
            const gitStatus = await runCommand(["git", "status", "--porcelain"]);

            if (gitStatus.trim() !== "") {
                // Stage all changes to check diff
                await runCommand(["git", "add", "-A"]);

                // Get a summary of changes
                const diffSummary = await runCommand(["git", "diff", "--staged", "--stat"]);

                if (commit) {
                    log.info(`Changes detected in ${adapterName}, committing...`);
                    log.info(`Changes summary: \n${diffSummary.trim()}`);

                    // Commit changes with a descriptive message
                    const commitMessage =
                        `chore: generate ${adapter} themes with latest core definitions`;

                    await runCommand([
                        "git",
                        "commit",
                        "-m",
                        commitMessage,
                        "-m",
                        "Auto-generated by black-atom-core",
                        "-m",
                        `🤖 Generated with black-atom-core`,
                    ]);

                    log.success(`Successfully committed changes to ${adapter}`);
                } else {
                    log.info(`Changes detected in ${adapterName}, but not committing.`);

                    // Reset staging since we're not committing
                    await runCommand(["git", "reset"]);
                }
            } else {
                log.info(`No changes detected in ${adapterName}`);
            }
        },
        { title },
    );
}
