import { forEachAdapter, runCommand } from "./utils.ts";
import log from "../../lib/log.ts";
import { dirname, join } from "@std/path";
import { config } from "../../config.ts";

/**
 * Options for generating themes in repositories
 */
export interface AdaptRepositoriesOptions {
    /** Whether to commit changes (default: true) */
    commit?: boolean;
    /** Whether to log errors immediately (useful for initial generation) */
    logErrors?: boolean;
}

/**
 * Generate themes for all repositories and optionally commit changes
 */
export async function generateAllRepositories(
    { commit = true, logErrors = false }: AdaptRepositoriesOptions = {},
) {
    const results: { adapter: string; hasChanges: boolean; error?: string }[] = [];

    await forEachAdapter(
        async ({ adapter, adapterName }) => {
            try {
                // Run black-atom-core generate command to ensure fresh module loading
                const cmd = new Deno.Command("black-atom-core", {
                    args: ["generate"],
                    stdout: "inherit",
                    stderr: "inherit",
                });
                
                const { success } = await cmd.output();
                if (!success) {
                    throw new Error("Generate command failed");
                }

                // Check for changes
                const gitStatus = await runCommand(["git", "status", "--porcelain"]);
                const hasChanges = gitStatus.trim() !== "";

                if (hasChanges) {
                    // Stage all changes to check diff
                    await runCommand(["git", "add", "-A"]);

                    // Get a summary of changes
                    const diffSummary = await runCommand(["git", "diff", "--staged", "--stat"]);

                    if (commit) {
                        log.info(`Changes detected in ${adapterName}, committing...`);
                        log.info(`Changes summary: \n${diffSummary.trim()}`);

                        // Commit changes with a descriptive message
                        const commitMessage =
                            `chore: generate ${adapter} themes with latest core definitions`;

                        await runCommand([
                            "git",
                            "commit",
                            "-m",
                            commitMessage,
                            "-m",
                            "Auto-generated by black-atom-core",
                            "-m",
                            `🤖 Generated with black-atom-core`,
                        ]);

                        log.success(`Successfully committed changes to ${adapter}`);
                    } else {
                        // Reset staging since we're not committing
                        await runCommand(["git", "reset"]);
                    }
                }

                results.push({ adapter, hasChanges });
            } catch (error) {
                const errorMsg = error instanceof Error ? error.message : String(error);
                results.push({ adapter, hasChanges: false, error: errorMsg });

                // Log error immediately if requested (useful for initial generation)
                if (logErrors) {
                    log.error(`Error in ${adapterName}: ${errorMsg}`);
                }
            }
        },
    );

    return results;
}

/**
 * Generate themes for a specific adapter using the existing generate command
 */
export async function generateSingleAdapter(
    adapterName: string,
): Promise<{ adapter: string; hasChanges: boolean; error?: string }> {
    const orgDir = config.dir.org || join(dirname(config.dir.core), config.orgName);
    const adapterDir = join(orgDir, adapterName);
    const coreDir = config.dir.core;

    try {
        // Change to adapter directory
        Deno.chdir(adapterDir);

        // Run black-atom-core generate command to ensure fresh module loading
        const cmd = new Deno.Command("black-atom-core", {
            args: ["generate"],
            stdout: "inherit",
            stderr: "inherit",
        });
        
        const { success } = await cmd.output();
        if (!success) {
            throw new Error("Generate command failed");
        }

        // Check for changes
        const gitStatus = await runCommand(["git", "status", "--porcelain"]);
        const hasChanges = gitStatus.trim() !== "";

        if (hasChanges) {
            // Reset staging since we're not committing
            await runCommand(["git", "reset"]);
        }

        return { adapter: adapterName, hasChanges };
    } catch (error) {
        const errorMsg = error instanceof Error ? error.message : String(error);
        return { adapter: adapterName, hasChanges: false, error: errorMsg };
    } finally {
        // Always return to core directory
        Deno.chdir(coreDir);
    }
}
