/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewUiRouteImport } from './routes/preview/ui'
import { Route as PreviewSyntaxRouteImport } from './routes/preview/syntax'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewUiRoute = PreviewUiRouteImport.update({
  id: '/preview/ui',
  path: '/preview/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewSyntaxRoute = PreviewSyntaxRouteImport.update({
  id: '/preview/syntax',
  path: '/preview/syntax',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preview/syntax': typeof PreviewSyntaxRoute
  '/preview/ui': typeof PreviewUiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preview/syntax': typeof PreviewSyntaxRoute
  '/preview/ui': typeof PreviewUiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/preview/syntax': typeof PreviewSyntaxRoute
  '/preview/ui': typeof PreviewUiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/preview/syntax' | '/preview/ui'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/preview/syntax' | '/preview/ui'
  id: '__root__' | '/' | '/preview/syntax' | '/preview/ui'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreviewSyntaxRoute: typeof PreviewSyntaxRoute
  PreviewUiRoute: typeof PreviewUiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/ui': {
      id: '/preview/ui'
      path: '/preview/ui'
      fullPath: '/preview/ui'
      preLoaderRoute: typeof PreviewUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/syntax': {
      id: '/preview/syntax'
      path: '/preview/syntax'
      fullPath: '/preview/syntax'
      preLoaderRoute: typeof PreviewSyntaxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreviewSyntaxRoute: PreviewSyntaxRoute,
  PreviewUiRoute: PreviewUiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
